### ISSUE TITLE
"사진 추가" 화면에서 사진 삭제시 boder가 깜빡이는 문제

### ISSUE THREAD

**Issue by ezreal12** [mhwan/PicA#1]
![11](https://user-images.githubusercontent.com/18520284/73685559-b2e74480-4709-11ea-96c3-b19e03610e15.PNG)

위의 화면에서 리사이클러뷰의 아이템(사진)이 삭제될경우 사진의 boder가 깜빡이는 현상 발생

----대화 전문

[배명환 선배님] [오전 4:21] 근데 아쉬운게 두가지 있는거같은데
[박희수] [오전 4:21] 어느거요 ㅇ.ㅇ?!
[배명환 선배님] [오전 4:21] 이게 핸들러를 사용해서 그런지
[배명환 선배님] [오전 4:21] 내가 현재 보고있는 border가 표시된화면말고
[배명환 선배님] [오전 4:21] 다른 사진을 삭제하면
[배명환 선배님] [오전 4:22] 현재 보고있는 사진의 border가 잠시 깜빡거리면서 다시 선택되는게
[배명환 선배님] [오전 4:22] 아주 살짝 보이더라구요ㅠ
[박희수] [오전 4:22] 헐 맞아 그건 핸들러가 아니고 리사이클러뷰가 갱신됬을때 포커스같은 문제때문일거에요
[박희수] [오전 4:22] ㅠ
[배명환 선배님] [오전 4:23] 아하
[배명환 선배님] [오전 4:23] 갱신됬을때 그럼 해당 뷰는 change가 안되게 하면 되지 않나요?!
[박희수] [오전 4:23] 음..그부분은 어떻게 해야할지 잘 모르겠어요
[박희수] [오전 4:24] 삭제하고 데이터가 변경됬을때 "변경됬다"고 알려주면 뷰가 다시그리는거라
[박희수] [오전 4:24] 어떻게 풀수있을지 조금 애매해요 ㅠ
[배명환 선배님] [오전 4:24] 아 그 있어요
[배명환 선배님] [오전 4:24] recyclerview는 리스트뷰와달리
[배명환 선배님] [오전 4:25] notifydatasetchanged 있잖아요
[배명환 선배님] [오전 4:25] 그게 매우 여러종류로 있어요
[박희수] [오전 4:25] 네 ㅇ.ㅇ!
[박희수] [오전 4:25] 헐
[배명환 선배님] [오전 4:25] add될때 remove될때 다 적절한 효과가 적용되도록
[배명환 선배님] [오전 4:25] 다 다르게 나눠져있어요ㅎ

**Comment by mhwan** [comment]
recyclerViewAdapter의 notifyItemRemoved(id)는 인덱스가 현재 포커싱된거에서 다음 인덱스로 넘어가는 현상발생함
